---
- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: reload consul
  sudo: yes
  command: systemctl reload consul
  notify:
    - wait for consul to listen

- name: wait for consul to listen
  command: /usr/bin/smlr http localhost:8500/v1/catalog/nodes

- name: reload consul-template
  sudo: yes
  command: systemctl reload consul-template
